import React from "react";
export const ProductList=[
            {   
                id:1,
                Brand:"BERSACHE",
                details:"Sports Shoes for Men |Latest Stylish Sports Shoes for Men |Lace-Up",
                department:'Mens Running Shoes',
                oldprice:1500,
                newprice:1250,
                rating:"4",
                rateimg:"../str4.png",
                size:[5,8.5,4.5],
                color:"red",
                photo: "https://m.media-amazon.com/images/I/517w5lVaUjL._AC_UL480_FMwebp_QL65_.jpg"
            },
            {
                id:2,
                Brand:"ASIAN",
                details:"Men's Wonder-13 Sports Running Shoes",
                department:'Mens Walking Shoes',
                oldprice:752,
                newprice:300,
                rating:"5",
                rateimg:"../str4.png",
                size:[5,5.5,9],
                color:"black",
                photo: "https://m.media-amazon.com/images/I/41l2imvuWJL._AC_UL480_QL65_.jpg"
            },
            {
                id:3,
                Brand:"CRKAS",
                details:"Men's running Shoes",
                department:'Mens Running Shoes',
                oldprice:634,
                newprice:150,
                rating:"3",
                rateimg:"../str3.png",
                size:[5,8.5,9.5],
                color:"gold",
                photo: "https://m.media-amazon.com/images/I/81gjWDTiJSL._AC_UL480_QL65_.jpg"
            },
            {
                id:4,
                Brand:"SPARX",
                details:"Mens Sd0323g Sneakers",
                department:'Mens Walking Shoes',
                oldprice:2500,
                newprice:1400,
                rating:"3",
                rateimg:"../str3.png",
                size:[7,8.5,9.5],
                color:"white",
                photo: "https://m.media-amazon.com/images/I/61U5JL9EZTL._AC_UL480_QL65_.jpg"
        
            },
            {
                id:5,
                Brand:"KNOOS",
                details:"Men's Loafer",
                department:'Mens Walking Shoes',
                oldprice:1250,
                newprice:999,
                rating:"1",
                rateimg:"../str1.png",
                size:[7,5.5,8.5],
                color:"yellow",
                photo: "https://m.media-amazon.com/images/I/71UigI6ggOL._AC_UL480_QL65_.jpg"
            },
            {
                id:6,
                Brand:"CAMPUS",
                details:"Mens Oxyfit Running Shoe; Sport Shoe",
                department:'Womens Athletic Shoes',
                oldprice:584,
                newprice:100,
                rating:"2",
                rateimg:"../str2.png",
                size:[7,8.5,5.5],
                color:"pink",
                photo: "https://m.media-amazon.com/images/I/81udesQtZYL._AC_UL480_QL65_.jpg"
            },
            {
                id:7,
                Brand:"CENTRINO",
                details:"Men's Rso161 Walking Shoe",
                department:'Mens Running Shoes',
                oldprice:358,
                newprice:50,
                rating:"5",
                rateimg:"../str4.png",
                size:[8.5,8,9],
                color:"orange",
                photo: "https://m.media-amazon.com/images/I/81PhZXAAJjL._AC_UL480_QL65_.jpg"
            },
            {
                id:8,
                Brand:"BOURGE",
                details:"Bourge Men's Sublite Cushion Safety Toe Athletic Work Shoe Industrial & Construction",
                department:'Womens Athletic Shoes',
                oldprice:987,
                newprice:654,
                rating:"2",
                rateimg:"../str2.png",
                size:[8,4.5,5.5],
                color:"green",
                photo: "https://m.media-amazon.com/images/I/71igvwezNiL._AC_UL480_QL65_.jpg"
            },
            {
                id:9,
                Brand:"TRASE",
                details:"Men's Lace Up Formals, Office Wear",
                department:'Womens Athletic Shoes',
                oldprice:953,
                newprice:844,
                rating:"1",
                rateimg:"./str1.png",
                size:[8,5,9],
                color:"brown",
                photo: "https://m.media-amazon.com/images/I/81qfQO5PwOL._AC_UL480_FMwebp_QL65_.jpg"
            },
            {
                id:10,
                Brand:"ASIAN",
                details:"New Balance Men's 623 V3 Casual Comfort Cross Trainer",
                department:'Girls Athletic Shoes',
                oldprice:684,
                newprice:594,
                rating:"4",
                rateimg:"../str4.png",
                size:[5,9,8.5],
                color:"gold",
                photo: "https://m.media-amazon.com/images/I/91ebmBHLvML._AC_UL480_QL65_.jpg"
            },{
                id:11,
                Brand:"CAMPUS",
                details:"Merrell Men's Trail Glove 6 Sneaker",
                department:'Mens Running Shoes',
                oldprice:784,
                newprice:454,
                rating:"5",
                rateimg:"../str4.png",
                size:[9,8,7],
                color:"silver",
                photo: "https://m.media-amazon.com/images/I/81Yoj1YOPaL._AC_UL480_QL65_.jpg"
            },
            {
                id:12,
                Brand:"ASIAN",
                details:"Under Armour Men's Street Encounter Iv CNV",
                department:'Mens Walking Shoes',
                oldprice:754,
                newprice:524,
                rating:"1",
                rateimg:"../str1.png",
                size:[9,5,8],
                color:"green",
                photo: "https://m.media-amazon.com/images/I/71r0uVVVPBL._AC_UL640_QL65_.jpg"
            },{
                id:13,
                Brand:"CAMPUS",
                details:"Clarks Men's Tilden Cap Oxford Shoe",
                department:'Womens Athletic Shoes',
                oldprice:1000,
                newprice:852,
                rating:"3",
                rateimg:"../str3.png",
                size:[5.5,8,6],
                color:"white",
                photo: "https://m.media-amazon.com/images/I/61QHck6lpgL._AC_UL480_FMwebp_QL65_.jpg"
            },{
                id:14,
                Brand:"ASIAN",
                details:"Mens Oxyfit Running Shoe; Sport Shoe",
                department:'Girls Athletic Shoes',
                oldprice:1084,
                newprice:999,
                rating:"5",
                rateimg:"../str4.png",
                size:[5.5,8,9],
                color:"black",
                photo: "https://m.media-amazon.com/images/I/71p1iVHjEQL._AC_UL480_QL65_.jpg"
            },{
                id:15,
                Brand:"CAMPUS",
                details:"Men's Loafer",
                department:'Boys Athletic Shoes',
                oldprice:984,
                newprice:694,
                rating:"3",
                rateimg:"../str3.png",
                size:[7.5,8,6],
                color:"red",
                photo: "https://m.media-amazon.com/images/I/8104Vvbz35L._AC_UL480_FMwebp_QL65_.jpg"
            },{
                id:16,
                Brand:"CAMPUS",
                details:"ASICS Kid's Matflex 6 Grade School Wrestling Shoes",
                department:'Girls Athletic Shoes',
                oldprice:786,
                newprice:675,
                rating:"2",
                rateimg:"../str2.png",
                size:[8.5,8,6],
                color:"orange",
                photo: "https://m.media-amazon.com/images/I/81PhZXAAJjL._AC_UL480_QL65_.jpg"
            },{
                id:17,
                Brand:"CAMPUS",
                details:"Men's Rso161 Walking Shoe",
                department:'Boys Athletic Shoes',
                oldprice:584,
                newprice:494,
                rating:"1",
                rateimg:"../str1.png",
                size:[9.5,8,6],
                color:"white",
                photo: "https://m.media-amazon.com/images/I/51MIYAhk91L._AC_UL480_QL65_.jpg"
            },{
                id:18,
                Brand:"Under Armour",
                details:"Under Armour Unisex Child Grade School Assert 9 Running Shoe",
                department:'Womens  Running Shoes',
                oldprice:852,
                newprice:741,
                rating:"3",
                rateimg:"../str3.png",
                size:[8.5,8,9],
                color:"black",
                photo: "https://m.media-amazon.com/images/I/81kVwBkV2iL._AC_UL480_QL65_.jpg"
            },{
                id:19,
                Brand:"PUMA",
                details:"PUMA Unisex-Child Axelion Running Shoe",
                department:'Girls Athletic Shoes',
                oldprice:953,
                newprice:752,
                rating:"2",
                rateimg:"../str2.png",
                size:[5.5,6,8],
                color:"black",
                photo: "https://m.media-amazon.com/images/I/81VX+mKLHeL._AC_UL480_QL65_.jpg"
            },{
                id:20,
                Brand:"adidas",
                details:"Columbia Unisex-Child Redmond Waterproof Hiking Shoe",
                department:' Boys Athletic Shoes',
                oldprice:857,
                newprice:744,
                rating:"5",
                rateimg:"../str4.png",
                size:[9.5,6,8],
                color:"red",
                photo: "https://m.media-amazon.com/images/I/81pC6yCwY5L._AC_UL480_FMwebp_QL65_.jpg"
            },{
                id:21,
                Brand:"BOURGE",
                details:"New Balance Kid's 888 V2 Lace-Up Running Shoe",
                department:'Womens  Running Shoes',
                oldprice:787,
                newprice:364,
                rating:"3",
                rateimg:"../str3.png",
                size:[8.5,5,6],
                color:"blue",
                photo: "https://m.media-amazon.com/images/I/51N9LYNfAVL._AC_UL480_QL65_.jpg"
            },{
                id:21,
                Brand:"Under Armour",
                details:"Under Armour Unisex-Child Pre-School Zone Bb Basketball Shoe",
                department:'Womens  Running Shoes',
                oldprice:667,
                newprice:554,
                rating:"2",
                rateimg:"../str2.png",
                size:[8.5,9,],
                color:"red",
                photo: "https://m.media-amazon.com/images/I/71F5chCXQqS._AC_UL480_FMwebp_QL65_.jpg"
            },{
                id:22,
                Brand:"PUMA",
                details:"Native Shoes, Jefferson Child, Kids Lightweight Sneaker",
                department:'Boys Athletic Shoes',
                oldprice:967,
                newprice:634,
                rating:"4",
                rateimg:"../str4.png",
                size:[9.5,5,8],
                color:"gold",
                photo: "https://m.media-amazon.com/images/I/91JSyr6uGsL._AC_UL480_QL65_.jpg"
            },{
                id:23,
                Brand:"BOURGE",
                details:"Simple Joys by Carter's Unisex Kids and Toddlers' Daniel High-Top Sneaker",
                department:'Womens  Running Shoes',
                oldprice:1287,
                newprice:1004,
                rating:"4",
                rateimg:"../str4.png",
                size:[9,8.7],
                color:"silver",
                photo: "https://m.media-amazon.com/images/I/71Nk5eUU4cL._AC_UL480_QL65_.jpg"
            },{
                id:24,
                Brand:"adidas",
                details:"adidas Unisex-Child Ownthegame 2.0  Shoe",
                department:' Mens Athletic Shoes',
                oldprice:987,
                newprice:644,
                rating:"1",
                rateimg:"../str1.png",
                size:[8,9.5,5],
                color:"violet",
                photo: "https://m.media-amazon.com/images/I/71hknvVXswL._AC_UL480_QL65_.jpg"
            },{
                id:25,
                Brand:"Nike",
                details:"Nike Kids Flex Runner",
                department:'Womens  Running Shoes',
                oldprice:887,
                newprice:684,
                rating:"5",
                rateimg:"../str4.png",
                size:[4,5.5,6.5],
                color:"yellow",
                photo: "https://m.media-amazon.com/images/I/91I7-XBsBBS._AC_UL480_QL65_.jpg"
            },{
                id:26,
                Brand:"BOURGE",
                details:"Sperry Men's Striper II CVO Washable Sneaker",
                department:'Womens Walking Shoes',
                oldprice:1000,
                newprice:500,
                rating:"2",
                rateimg:"../str2.png",
                size:[4.5,6,9.5],
                color:"green",
                photo: "https://m.media-amazon.com/images/I/61jokOM4GqL._AC_UL480_QL65_.jpg"
            },{
                id:27,
                Brand:"Nike",
                details:"Nike Kids Flex Runner (Big Kid)",
                department:'Womens Walking Shoes',
                oldprice:1000,
                newprice:899,
                rating:"1",
                rateimg:"../str1.png",
                size:[4.5,5,9.5],
                color:"orange",
                photo: "https://m.media-amazon.com/images/I/81I1huqQYYS._AC_UL480_QL65_.jpg"
            },{
                id:28,
                Brand:"Reebok",
                details:"Nautica Men's Casual Shoe,Classic Low Top Loafer, Fashion Sneaker (Lace-Up/Slip-On)",
                department:'Mens Athletic Shoes',
                oldprice:957,
                newprice:759,
                rating:"5",
                rateimg:"../str4.png",
                size:[4,5,6],
                color:"pink",
                photo: "https://m.media-amazon.com/images/I/71Bu3WYr7tL._AC_UL480_FMwebp_QL65_.jpg"
            },
            {
                id:29,
                Brand:"BOURGE",
                details:"New Balance Men's 410 V7 Trail Running Shoe",
                department:'Womens Walking Shoes',
                oldprice:856,
                newprice:426,
                rating:"1",
                rateimg:"../str1.png",
                size:[6.5,8,9],
                color:"gray",
                photo: "https://m.media-amazon.com/images/I/519Ta0g3p0L._AC_UL480_QL65_.jpg"
            },{
                id:30,
                Brand:"Reebok",
                details:"Whatseaso Mens Womens Water Shoes Quick Dry Barefoot Shoes for Diving ",
                department:' Mens Athletic Shoes',
                oldprice:520,
                newprice:420,
                rating:"2",
                rateimg:"../str2.png",
                size:[6,8,6.5],
                color:"violet",
                photo:"https://m.media-amazon.com/images/I/51aB69NnLlL._AC_UL480_QL65_.jpg"
            },
            {
                id:31,
                type:"mobiles",
                Brand:"APPLE",
                details:"Apple iPhone 13 Pro Max, 128GB, Sierra Blue - Unlocked (Renewed)",
                department:'',
                oldprice:119530,
                newprice:118440,
                rating:"1",
                rateimg:"./str1.png",
                size:[9,4,5],
                color:"blue",
                photo:  "https://m.media-amazon.com/images/I/61FZC+6hDFL._AC_UY327_FMwebp_QL65_.jpg"
            },
        
            {
                id:32,
                type:"mobiles",
                Brand:"OPPO",
                details:"OPPO Find X5 Lite Dual-SIM 256GB ROM + 8GB RAM (GSM Only | No CDMA) Factory Unlocked 5G Smartphone (Starlight Black) - International Version",
                department:'',
                oldprice:18983,
                newprice:16833,
                rating:"1",
                rateimg:"./str1.png",
                size:[9,4,5],
                color:"blue",
                photo:  "https://m.media-amazon.com/images/I/61e3H8mlJ9L._AC_UY327_FMwebp_QL65_.jpg"
            },
            {
                id:33,
                type:"mobiles",
                Brand:"HONOR",
                details:"Honor 50 Dual-SIM 128GB ROM + 6GB RAM (GSM | CDMA) Factory Unlocked 5G Smartphone (Emerald Green) - International Version",
                department:'',
                oldprice:15953,
                newprice:14844,
                rating:"1",
                rateimg:"./str1.png",
                size:[9,4,5],
                color:"green",
                photo:  "https://m.media-amazon.com/images/I/61fLymuGTwL._AC_UY327_FMwebp_QL65_.jpg"
            },
            {
                id:34,
                type:"mobiles",
                Brand:"REDMI",
                details:"REDMI  S20 FE G780G 4G Dual 128GB 8GB RAM ",
                department:'',
                oldprice:11953,
                newprice:10844,
                rating:"1",
                rateimg:"./str1.png",
                size:[9,4,5],
                color:"orange",
                photo:  "https://m.media-amazon.com/images/I/71Gkxao9EHL._AC_UY327_QL65_.jpg"
            },
            {
                id:35,
                type:"mobiles",
                Brand:"SUMSUNG",
                details:"SAMSUNG Galaxy S22+ Cell Phone, Factory Unlocked Android Smartphone, 128GB, 8K Camera & Video, Brightest Display Screen",
                department:'',
                oldprice:29535,
                newprice:28440,
                rating:"1",
                rateimg:"./str1.png",
                size:[9,4,5],
                color:"pink",
                photo:  "https://m.media-amazon.com/images/I/81m32nRviEL._AC_UY327_FMwebp_QL65_.jpg"
            },
            {
                id:36,
                type:"mobiles",
                Brand:"NOKIA",
                details:"Nokia XR20 5G | Android 11 | Unlocked Smartphone | Dual SIM | US Version | 6/128GB | 6.67-Inch Screen | 48MP Dual Camera | Granite",
                department:'',
                oldprice:19530,
                newprice:18440,
                rating:"1",
                rateimg:"./str1.png",
                size:[9,4,5],
                color:"black",
                photo:  "https://m.media-amazon.com/images/I/71Ptb2ttfaS._AC_UY327_FMwebp_QL65_.jpg"
            },
           
        
        
        
        ];
         
    
    